on:
  # can trigger the workflow manually
  workflow_dispatch:
  # also runs on schedule, every Tuesday at 8.15am
  schedule:
    - cron: '15 08 * * 2'

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        # Running on mac as it's quicker to build
          - {os: macOS-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install poppler
        run: brew install poppler
      
      - name: Restore renv snapshot
        shell: Rscript {0}
        run: |
          if (!require('renv')) install.packages('renv')
          renv::restore()
          
      # Scrape and process new SAGE publications
      - name: Scrape
        run: Rscript update_sage_data.R
        
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git pull origin main
          git add data/SAGE_tables.rds
          git commit -am "GH ACTION Autorun $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
      - name: Push to shiny.io
        run: >
          Rscript
          -e "rsconnect::setAccountInfo(name='department-for-education', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')"
          -e "rsconnect::deployApp()"